matrix:
  include:
  - name: "Git use and project structure"
    language: bash
    os: linux
    script:
    - bash ./test/git_use.sh

  - name: "R code tests"
    language: r 
    os: linux
    script:
    - Rscript ./test/test.R